// <auto-generated />
namespace CJG.Infrastructure.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v010501 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v010501));
        
        string IMigrationMetadata.Id
        {
            get { return "201708171904187_v01.05.01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
