// <auto-generated />
namespace CJG.Infrastructure.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class v011001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v011001));
        
        string IMigrationMetadata.Id
        {
            get { return "201812051924359_v01.10.01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
