// <auto-generated />
namespace CJG.Infrastructure.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class v01140102 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v01140102));
        
        string IMigrationMetadata.Id
        {
            get { return "202001062349052_v01.14.01.02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
