// <auto-generated />
namespace CJG.Infrastructure.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class v021701 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v021701));
        
        string IMigrationMetadata.Id
        {
            get { return "202601082203046_v02.17.01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
