PRINT 'Inserting [NotificationTypes]'
INSERT [dbo].[NotificationTypes]
 ([Id], [NotificationTemplateId], [RecipientType], [MilestoneDateOffset], [MilestoneDateName], [NotificationTypeName]) VALUES
 (01,  1, 0,   0, N'SubmittedDate',                 N'InsSubmittionAdmin')
,(02,  2, 0,   0, N'OfferIssueDate',                N'InsIssuedOfferAdmin')
,(03,  3, 0,   0, N'GrantAcceptedDate',             N'InsGrantAcceptedAdmin')
,(04,  4, 0,   5, N'OfferIssueDate',                N'SchAcceptingDeadlineAdmin')
,(05,  5, 0, -14, N'TrainingStartDate',             N'SchBeforeTraining14DaysAdmin')
,(06,  6, 0,  -5, N'TrainingStartDate',             N'SchBeforeTraining5DaysAdmin')
,(07,  7, 0,   1, N'TrainingStartDate',             N'SchAfterTraining1DayNoPartAdmin')
,(08,  8, 0,   1, N'TrainingStartDate',             N'SchAfterTraining1DayHasPartAdmin')
,(09,  9, 0,  14, N'TrainingStartDate',             N'SchAfterTraining14DaysAdmin')
,(10, 10, 0,  31, N'TrainingStartDate',             N'SchAfterTraining31DaysNoPartAdmin')
,(11, 11, 0,  31, N'TrainingStartDate',             N'SchAfterTraining31DaysHasPartAdmin')
,(12, 12, 0,   1, N'TrainingEndDate',               N'SchAfterTrainingEnd1DayAdmin')
,(13, 13, 0,  31, N'TrainingEndDate',               N'SchAfterTrainingEnd31DayNoRepAdmin')
,(14, 14, 0,   0, N'ChangeTrainingProviderApprove', N'InsChangeTrainingProviderApproveAdmin')
,(15, 15, 0,   0, N'ChangeTrainingProviderDeny',	N'InsChangeTrainingProviderDenyAdmin')
,(16,  5, 1, -14, N'TrainingStartDate',             N'SchBeforeTraining14DaysEmp')
,(17,  6, 1,  -5, N'TrainingStartDate',             N'SchBeforeTraining5DaysEmp')
,(18, 12, 1,   1, N'TrainingEndDate',               N'SchAfterTrainingEnd1DayEmp')
,(19, 13, 1,  31, N'TrainingEndDate',               N'SchAfterTrainingEnd31DayNoRepEmp')
,(20, 16, 0,   0, N'DateCancelled',                 N'InsCancelledByMinsitry')
,(21, 17, 0,   0, N'ClaimSumbitted',                N'InsClaimSubmitted')
,(22, 18, 0,   0, N'PaymentRequested',              N'InsPaymentRequested')
,(23, 19, 0,   0, N'ClaimDenied',                   N'InsClaimDenied')
,(24, 20, 0,   0, N'ClaimReturned',                 N'InsClaimReturned')
,(25, 21, 0,   0, N'ApplicationDenied',             N'InsApplicationDenied')
,(26, 22, 0,   0, N'OfferWithdrawn',                N'InsOfferWithdrawn')
,(27, 23, 0,   0, N'NotAccepted',                   N'InsNotAccepted')
