PRINT 'Inserting [Regions]'
INSERT [dbo].[Regions]
 ([Id], [CountryId], [IsActive], [RowSequence], [Name]) VALUES
 (N'AB', N'CA', 1, 0, N'Alberta')
,(N'BC', N'CA', 1, 0, N'British Columbia')
,(N'MB', N'CA', 1, 0, N'Manitoba')
,(N'NB', N'CA', 1, 0, N'New Brunswick')
,(N'NL', N'CA', 1, 0, N'Newfoundland and Labrador')
,(N'NS', N'CA', 1, 0, N'Nova Scotia')
,(N'NT', N'CA', 1, 0, N'Northwest Territories')
,(N'NU', N'CA', 1, 0, N'Nanavut')
,(N'ON', N'CA', 1, 0, N'Ontario')
,(N'PE', N'CA', 1, 0, N'Prince Edward Island')
,(N'QC', N'CA', 1, 0, N'Quebec')
,(N'SK', N'CA', 1, 0, N'Saskatchewan')
,(N'YT', N'CA', 1, 0, N'Yukon')

,(N'AK', N'US', 1, 0, N'Alaska')
,(N'AL', N'US', 1, 0, N'Alabama')
,(N'AZ', N'US', 1, 0, N'Arizona')
,(N'AR', N'US', 1, 0, N'Arkansas')
,(N'CA', N'US', 1, 0, N'California')
,(N'CO', N'US', 1, 0, N'Colorado')
,(N'CT', N'US', 1, 0, N'Connecticut')
,(N'DC', N'US', 1, 0, N'District of Columbia')
,(N'DE', N'US', 1, 0, N'Delaware')
,(N'FL', N'US', 1, 0, N'Florida')
,(N'GA', N'US', 1, 0, N'Georgia')
,(N'HI', N'US', 1, 0, N'Hawaii')
,(N'IA', N'US', 1, 0, N'Iowa')
,(N'ID', N'US', 1, 0, N'Idaho')
,(N'IL', N'US', 1, 0, N'Illinois')
,(N'IN', N'US', 1, 0, N'Indiana')
,(N'KS', N'US', 1, 0, N'Kansas')
,(N'KY', N'US', 1, 0, N'Kentucky')
,(N'LA', N'US', 1, 0, N'Louisiana')
,(N'MA', N'US', 1, 0, N'Massachusetts')
,(N'MD', N'US', 1, 0, N'Maryland')
,(N'ME', N'US', 1, 0, N'Maine')
,(N'MI', N'US', 1, 0, N'Michigan')
,(N'MN', N'US', 1, 0, N'Minnesota')
,(N'MO', N'US', 1, 0, N'Missouri')
,(N'MS', N'US', 1, 0, N'Mississippi')
,(N'MT', N'US', 1, 0, N'Montana')
,(N'NC', N'US', 1, 0, N'North Carolina')
,(N'ND', N'US', 1, 0, N'North Dakota')
,(N'NE', N'US', 1, 0, N'Nebraska')
,(N'NH', N'US', 1, 0, N'New Hampshire')
,(N'NJ', N'US', 1, 0, N'New Jersey')
,(N'NM', N'US', 1, 0, N'New Mexico')
,(N'NV', N'US', 1, 0, N'Nevada')
,(N'NY', N'US', 1, 0, N'New York')
,(N'OH', N'US', 1, 0, N'Ohio')
,(N'OK', N'US', 1, 0, N'Oklahoma')
,(N'OR', N'US', 1, 0, N'Oregon')
,(N'PA', N'US', 1, 0, N'Pennsylvania')
,(N'RI', N'US', 1, 0, N'Rhode Island')
,(N'SC', N'US', 1, 0, N'South Carolina')
,(N'SD', N'US', 1, 0, N'South Dakota')
,(N'TN', N'US', 1, 0, N'Tennessee')
,(N'TX', N'US', 1, 0, N'Texas')
,(N'UT', N'US', 1, 0, N'Utah')
,(N'VA', N'US', 1, 0, N'Virginia')
,(N'VT', N'US', 1, 0, N'Vermont')
,(N'WA', N'US', 1, 0, N'Washington')
,(N'WI', N'US', 1, 0, N'Wisconsin')
,(N'WV', N'US', 1, 0, N'West Virginia')
,(N'WY', N'US', 1, 0, N'Wyoming')