PRINT 'ADD COMMUNITIES 1 - 1000'

INSERT [dbo].[Communities] ([Caption], [IsActive], [RowSequence], [DateAdded], [DateUpdated])
VALUES
(N'100 Mile House – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'105 Mile House – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'108 Mile Ranch – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'111 Mile House – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'114 Mile House – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'12 Mile – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'122 Mile House – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'127 Mile House – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'141 Mile House – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'150 Mile House – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'40 Mile Flats – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'70 Mile House – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'93 Mile – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Abbotsford – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Abbott Heights – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Aberdeen – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Adams Lake – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Agassiz – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Agate – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Ahbau – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Ahousat – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Ainsworth – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Ainsworth Hot Springs – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Aiyansh – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Aiyansh 1 – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Akiskinook – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Alamo – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Albas – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Alberni – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Albert Canyon – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Albert Head – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Albion – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Albreda – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Aldergrove – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Alert Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Alexandria – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Alexis Creek – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Aleza Lake – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Alice Arm – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Alice Siding – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Alkali Lake – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Allenby – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Alliford Bay – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Allison Lake – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Almond Gardens – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Alpine Meadows – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Alta Lake – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Altona – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Alvin – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Ambleside – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Amsbury – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Anaconda – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Anahim Lake – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Anderson – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Anderson Subdivision – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Andimaul – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Anglemont – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Angusmac – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Anmore – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Anniedale – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Annis – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Anvil Island – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Anyox – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Anzac – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Appledale – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Applegrove – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Arbutus – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Arbutus Ridge – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Arden Park – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Ardmore – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Argenta – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Armstrong – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Arnold – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Arras – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Arrow Creek – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Arrow Park – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Arrowhead – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Arrowsmith – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Arrowview Heights – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Ashcroft – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Ashton Creek – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Aspen Grove – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Atbara – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Atchelitz – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Athalmer – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Atlin – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Atluck – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Atnarko – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Attachie – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Austin Heights – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Australian – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Avola – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Azouzetta – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Babcock Subdivision – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Baker – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Baker Creek – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Baldonnel – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Baldy Hughes – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Balfour – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Balmoral – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Balmoral Beach – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Bamberton – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Bamfield – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Bankeir – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Banks Island – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Bargain Harbour – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Bargain Harbour Sechelt Band 24 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Barkerville – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Barlow – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Barlow Creek – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Barnet – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Barnhartvale – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Barrett Lake – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Barriere – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Barrowtown – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Basford – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Basque – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Bastion Bay – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Batchelor Hills – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Bates Beach – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Baynes Lake – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Beach Grove – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Beachcomber – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Beachcomber Bay – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Bealby Point – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Bear Camp – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Bear Creek – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Bear Flat – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Bear Lake – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Beard''s Creek – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Beasley – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Beaton – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Beatton – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Beatton Ranch – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Beaver Cove – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Beaver Creek – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Beaver Falls – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Beaver Lake – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Beaver Pass House – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Beaver Point – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Beaverdell – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Beaverley – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Beavermouth – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Becher Bay 2 – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Becher House – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Bedwell Harbour – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Belcarra – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Belford – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Bell II – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Bella Bella – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Bella Coola – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Belleview – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Bellos – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Belmont Park – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Belvedere – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Bend – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Benledi – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Ben-My-Chree – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Bennett – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Benson Lake – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Benvoulin – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Beresford – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Bergs – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Beryl Prairie – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Bessborough – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Bestwick – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Bevan – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Big Bar – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Big Bar Creek – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Big Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Big Creek – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Big Eddy – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Big Lake – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Big Lake Ranch – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Big White Village – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Billings – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Billings Bay – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Birch Island – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Birchbank – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Birchdale – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Birchland Manor – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Birken – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Black Creek – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Black Pines – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Blackloam – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Blackpool – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Blackstock Subdivision – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Blackwater – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Blaeberry – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Blake – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Blakeburn – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Blewett – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Bligh Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Blind Bay – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Blind Channel – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Bliss Landing – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Bloedel – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Blowhole – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Blubber Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Blucher Hall – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Blue Hills – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Blue River – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Blue Springs – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Blueberry Creek – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Blueberry Farm – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Blueridge – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Boat Basin – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Boat Harbour – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Bob Quinn Lake – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Bold Point – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Bond – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Bonnet Hill – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Bonnington Falls – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Boothroyd (Part) 8A – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Boston Bar – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Boston Flats – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Boswell – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Bouchie Lake – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Boulder – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Boulder City – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Boulder Island Sechelt Band 25 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Boundary Bay – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Boundary Falls – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Bowen Island – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Bowser – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Box Lake – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Brackendale – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Bradner – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Braeloch – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Braemar Heights – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Braeside – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Bralorne – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Brandon – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Brandywine – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Brauns Island – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Brem River – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Brennan Creek – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Brentwood Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Brew Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Brexton – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Briar Ridge – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Bridal Falls – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Bridesville – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Bridge – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Bridge Lake – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Brigade Lake – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Brighouse – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Brighton Beach – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Brilliant – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Brisco – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Britannia Beach – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Broadview – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Brocklehurst – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Broman Lake – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Brookmere – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Brouse – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Browns Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Brownsville – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Brunswick – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Bryn – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Buccaneer Bay – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Buckhorn – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Buckinghorse River – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Buckley Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Buffalo Creek – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Buick – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Bulkley Canyon – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Bulkley House – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Bull Harbour – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Bull River – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Buntzen Bay – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Burke Road – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Burkeville – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Burnaby – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Burns Lake – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Burnt Flats – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Burton – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Butedale – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Cache Creek – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Caesars – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Cahilty – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Caithness – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Cale – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Callison Ranch – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Cambie – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Camborne – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Cameron Heights – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Cameron Lake – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Camp McKinney – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Campbell Creek – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Campbell Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Campbell River – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Campbellton – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Canal Flats – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Canford – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Canim – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Canim Lake – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Canoe – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Canoe River – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Canyon – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Canyon Alpine – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Canyon Heights – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Canyon Hot Springs – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Cariboo – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Cariboo Meadows – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Carlin – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Carlson – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Carmi – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Carmi Subdivision – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Carnaby – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Carp – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Carrolls Landing – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Carrs – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Carrs Landing – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Carson – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Cascade – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Casino – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Cassiar – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Cassidy – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Cassin – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Castle Rock – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Castledale – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Castlegar – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Caswell – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Cathedral – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Caulfeild – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Cawston – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Caycuse – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Cecil Lake – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Cedar – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Cedar Grove – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Cedar Heights Estates – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Cedarside – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Cedarvale – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Ceepeecee – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Celista – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Central Saanich – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Centreville – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Chaatl – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Chain Lake – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Chamiss Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Channel Ridge – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Chapman Camp – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Chapmans – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Charella Garden – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Charles – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Charlie Lake – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Charlotte Lake – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Chase – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Chase River – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Chasm – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Chaumox – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Cheakamus – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Cheam View – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Cheekye – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Chelohsin Sechelt Band 13 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Chemainus – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Cherry Creek – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Cherry Point – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Cherryville – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Ches-la-kee 3 – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Cheslatta – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Chetarpe – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Chetwynd – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Chezacut – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Chickwat Sechelt Band 9 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Chilanko Forks – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Chilcotin Forest – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Chilliwack – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Chilton Subdivision – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Chimney Valley – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'China Bar – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Chinook Cove – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Choate – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Chopaka – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Christian Valley – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Christina Lake – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Chu Chua – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Church House – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Chute Lake – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Cinema – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Cinnabar Valley – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Cisco – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Clairmont – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Clanwilliam – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Clapperton – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Clayburn – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Clayhurst – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Clayoquot – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Cleagh Creek – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Clearbrook – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Clearwater – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Clemina East – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Clemina West – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Clemretta – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Cleveland Park – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Cliffside – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Clinton – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Clode – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Clo-oose – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Coal Harbour – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Coal Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Coal River – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Coalmont – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Cobble Hill – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Cody – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Cokato – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Cokoqueneets Sechelt Band 23 – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Coldspring House – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Coldstream – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Coldwell Beach – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Colebank – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Colebrook – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'College Heights – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Collettville – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Colleymount – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Colquitz – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Columbia Gardens – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Columere Park – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Colvalli – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Colwood – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Comer – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Commodore Heights – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Comox – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Connaught Heights – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Conrad – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Coombe – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Coombs – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Cooper Creek – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Copper City – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Copper Cove – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Copper Creek – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Copper Mountain – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Coquitlam – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Coral Beach – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Corbin – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Cordova Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Cormorant Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Corra Linn – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Cortes Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Cortes Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Coryville – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Cottonwood – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Cottonwood Flats – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Couldwell Subdivision – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Courtenay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Coutlee – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Cove Cliff – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Cowans Point – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Cowichan Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Coykendahl – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Coyle – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Cracroft – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Craigellachie – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Cranberry – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Cranberry Junction – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Cranbrook – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Crawford Bay – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Creekside – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Creighton Valley – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Crescent Bay – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Crescent Beach – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Crescent Spur – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Crescent Valley – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Creston – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Crestwood Subdivision – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Criss Creek – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Crofton – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Crowsnest – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Croydon – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Crysdale – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Cultus Lake – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Cumberland – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Cumshewa – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Curzon – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Cypress Park – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Dallas – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Danskin – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'D''Arcy – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'D''Arcy Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Darfield – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Darrell Bay – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Dartmoor – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Dashwood – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Davidson – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Davis Bay – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Dawson Creek – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Dawsons Landing – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Days Ranch – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Day''s Subdivision – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'De Courcy Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Deadtree Point – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Deadwood – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Dease Lake – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Decker Lake – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Deep Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Deep Cove – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Deep Creek – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Deer Park – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Deerholme – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Defot – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Deka Lake – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Del Oro Subdivision – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Delkatla – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Delta – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Demean – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Denman Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Dentville – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Departure Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Deroche – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Devine – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Dewdney – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Dewey – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Digby Island – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Doe River – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Dog Creek – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Dogpatch – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Dogwood Valley – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Doig River – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Dokie – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Dokie Siding – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Dolan Road Subdivision – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Dollarton – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Dolphin Beach – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Dolphin Island 1 – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Dome Creek – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Donald – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Donald Landing – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Donnely Landing – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Doriston – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Dorreen – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Dot – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Douglas – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Douglas Hill Estates – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Douglas Lake – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Dove Creek – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Downie – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Dragon – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Drew Harbour – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Drewry – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Driftwood Creek – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Dry Gulch – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Drynoch – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'DuBose – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Duck Range – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Dufferin – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Dugan Lake – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Duncan – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Duncan Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Duncanby Landing – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Dunkley – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Dunsmuir – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Dunster – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Durieu – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Dutch Lake – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Eagle Bay – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Eagle Bluff – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Eagle Creek – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Eagle Harbour – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Eagle Heights – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Earls Cove – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'East Arrow Park – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'East Gate – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'East Kelowna – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'East Osoyoos – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'East Pine – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'East Sooke – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'East Thurlow Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'East Trail – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'East Wellington – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Eastbourne – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Eastgate – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Echo Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Ecoole – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Eddontenajon – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Eddy – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Edelweiss – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Edgewater – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Edgewood – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Egmont – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Egmont Sechelt Band 26 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Ehatisaht – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Eholt – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Ekins Point – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Ekwan – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Elephant Crossing – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Elk Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Elk Prairie – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Elkford – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Elko – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Elkview – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Elleh – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Ellison – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Elphinstone – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Encombe – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Endako – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Enderby – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Engen – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Engineer – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Enterprise – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Erickson – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Erie – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Errington – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Esler – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Esperanza – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Espinosa Inlet – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Esquimalt – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Estevan Point – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Evans – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Evelyn – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Evergreen Acres – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Ewing – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Exeter – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Exlou – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Exstew – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Extension – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Fair Harbour – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Fairbridge – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Fairfield – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Fairmont – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Fairmont Hot Springs – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Fairview – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Fairview Subdivision – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Falkland – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Falls – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Falls Creek – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Fallsway – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'False Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Fanny Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Farmington – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Farrell Creek – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Farron – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Faulder – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Fauquier – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Federal Ranch – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Fellers Heights – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Fenwick – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Ferguson – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Ferndale – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Fernie – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Fernwood – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Field – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Fife – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Fifth Cabin – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Fill – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Finmoore – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Fintry – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Fireside – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Firvale – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Fitzwilliam – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Five Mile – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Flat Creek – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Flathead – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Flatrock – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Fleetwood – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Fleming – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Floods – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Flores Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Flying U – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Fontas – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Fontas 1 – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Forde – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Fording – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Foreman – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Forest Grove – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Forest Hills – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Forest Knolls – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Forestdale – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Fort Babine – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Fort Fraser – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Fort Langley – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Fort Nelson – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Fort Nelson 2 – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Fort Rupert – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Fort St. James – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Fort St. John – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Fort Steele – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Foss – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Foster – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Fosthall – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Fountain – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Fountain Valley – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Fourth Cabin – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Fowler – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Fox Mountain – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Fraine – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Francis Lake – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Francis Peninsula – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Franklin Camp – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Fraser – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Fraser Heights – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Fraser Lake – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Fraserview – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Frederick – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'French Creek – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Fruitvale – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Fry Creek – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Fulford Harbour – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Furry Creek – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Gabriola – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Gabriola Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Galena – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Galiano – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Galiano Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Gallagher Lake – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Galloway – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Gambier Harbour – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Gang Ranch – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Ganges – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Garbitt – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Garden Bay – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Garden Village – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Garibaldi – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Garibaldi Estates – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Garibaldi Highlands – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Garnet Rock Trailer Court – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Garnet Valley – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Gates – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Gateway – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Gellatly – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Genelle – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Genoa Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'George River – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Georgetown Mills – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Germansen Landing – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Gerow Island – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Gerrard – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Gibbs – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Gibraltar – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Gibson Creek – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Gibsons – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Gifford – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Gill Island – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Gillies Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Gilpin – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Giscome – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Gitanyow – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Gitwinksihlkw – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Glacier – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Glacier Gulch – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Glade – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Gladwin – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Gleam – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Glen Fraser – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Glen Lake – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Glen Valley – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Glen Vowell – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Glenannan – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Glenbank – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Glenbrooke North – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Glendale – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Gleneagles – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Gleneden – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Glenemma – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Glenlily – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Glenmerry – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Glenmore – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Glenogle – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Glenora – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Glenrosa – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Glentanna – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Glimpse Lake – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Goat River – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Goatfell – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Gold Bridge – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Gold River – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Golden – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Good Hope – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Good Hope Lake – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Goodlow – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Goose Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Gordon River – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Gorge Harbour – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Gosnell – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Gossen Creek – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Gossip Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Gower Point – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Graham – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Graham Island – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Gramsons – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Grand Forks – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Grand Haven – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Grand Rapids – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Grand Trunk – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Granduc – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Grandview Bench – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Granisle – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Granite – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Granite Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Granite Falls – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Grant Brook – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Grantham – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Granthams Landing – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Grasmere – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Grassy Plains – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Gravelle Ferry – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Gray Creek – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Great Central – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Great Central Lake – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Greata – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Greeley – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Green Bay Resort – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Green Cove – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Green River – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Greendale – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Greenhills – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Greening – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Greenville – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Greenwood – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Griffith – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Grindrod – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Groundbirch – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Gun Lake – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Gundy – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Gutah – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Hagensborg – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Hagwilget – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Haig – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Haina – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Haisla – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Halfmoon Bay – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Halfway Ranch – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Hall – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Halliday – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Hanbury – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Hanceville – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Hansard – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Happy Valley – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Harbour Chines – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Harbour Village – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Hardwicke Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Harmac – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Harmer – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Harrison Hot Springs – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Harrison Mills – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Harrogate – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Harrop – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Hart Highlands – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Hartley Bay – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Harvey – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Harwood Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Hasler Flat – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Hastings-Sunrise – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Hatzic – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Hawkins Lake Subdivision – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Hawks – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Haysport – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Hayward – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Hazelmere – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Hazelton – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Headquarters – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Headwaters Ranch – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Health Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Hecate – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Hector – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Hedley – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Heffley Creek – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Hells Gate – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Hemlock Valley – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Hendrix Lake – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Heriot Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Hernando Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Hesquiat – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Heydon Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Hickethier Ranch – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Hicks – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Highlands – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Hillbank – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Hillcrest – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Hilliers – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Hills – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Hippa – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Hiusta Meadow – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Hixon – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Hkusam – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Hodda – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Holachten 8 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Holberg – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Hollyburn – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Holmwood – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Homfray Creek – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Honeymoon Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Honeymoon Creek – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Hope – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Hope Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Hope Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Hopetown – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Hopkins Landing – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Hornby Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Horse Creek – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Horsefly – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Hosmer – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Hospital Hill – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Hot Springs Cove – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Houston – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Howser – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Huble – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Hudson''s Hope – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Hulatt – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Hulcross – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Hullcar – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Humpback Bay – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Hunaechin Sechelt Band 11 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Huntingdon – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Huntington – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Hunts Inlet – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Hupel – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Huscroft – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Hutchinson – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Hutchison – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Hutton – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Hyacinthe Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Hyde Creek – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Hydraulic – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Hyland Post – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Illecillewaet – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Imperial Ranchettes – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Indian Rock – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Ingenika Mine – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Inkaneep – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Inkitsaph – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Invermere – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Irvine – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Irvines Landing – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Iskut – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Island Cache – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Isle Pierre – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Jackfish Lake Subdivision – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Jackman – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Jackson Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Jacksons – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Jade City – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Jaffray – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Jaleslie – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'James Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Jayem – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Jedway – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Jellicoe – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Jersey – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Jervis Inlet – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Jesmond – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Jeune Landing – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Jim Smith Lake and Area – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Johnson – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Johnsons Landing – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Jordan River – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'June Springs Estates – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Juniper Ridge – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Jura – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Juskatla – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Kahntah – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Kahntah 3 – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Kaisun – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Kakawis – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Kalamalka – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Kaleden – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Kaleva – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Kallum – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Kamloops – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Kanaka – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Kanaka Bar – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Kaslo – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Katz – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Keating – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Keats Island – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Kedleston – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Keefers – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Keekwillie Trailer Park – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Keithley Creek – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Kelly Lake – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Kelowna – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Kemano – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Kemano Beach – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Kendrick Camp – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Kennedy – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Kent – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Keremeos – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Kerr Creek – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Kersley – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Kettle Valley – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Kidd – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Kilbella Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Kildala Arm – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Kildonan – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Kilgard – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Kilkerran – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Killiney Beach – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Killy – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Kimberley – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Kimsquit – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Kincolith – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Kingcome – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Kingcome Inlet – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Kingfisher – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Kingsgate – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Kingsvale – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Kinnaird – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Kiskatinaw – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Kispiox – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Kispiox Valley – North Coast', 1, 0, GETUTCDATE(), NULL)