PRINT 'ADD COMMUNITIES 1001 - 2000'

INSERT [dbo].[Communities] ([Caption], [IsActive], [RowSequence], [DateAdded], [DateUpdated])
VALUES
(N'Kissick – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Kitamaat Village – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Kitchener – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Kitimat – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Kitkatla – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Kitsault – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Kitseguecla – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Kitselas – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Kitsumkalum – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Kitty Coleman – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Kitwanga – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Kiusta – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Klaalth Sechelt Band 5 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Klayekwim Sechelt Band 6 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Klayekwim Sechelt Band 6A – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Klayekwim Sechelt Band 7 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Klayekwim Sechelt Band 8 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Kleecoot – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Kleena Kleene – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Kleindale – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Klemtu – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Klua – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Knockholt – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Knutsford – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Kobes – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Kokish – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Koksilah – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Komo – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Kootenay Bay – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Kootenay Crossing – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Kootenay Landing – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Koster – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Kragmont – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Krestova – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Kuldo – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Kulkayu – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Kung – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Kuper Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Kuskonook – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Kwinitsa – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Kye Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Kyuquot – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Lac la Hache – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Lac Le Jeune – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Lachkaltsap 9 – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Ladysmith – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Lafferty – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Laidlaw – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Lakahahmen 11 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Lake Buntzen – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Lake Country – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Lake Cowichan – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Lake Errock – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Lake Kathlyn – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Lakelse – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Lakelse Lake – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Laketon – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Lakeview Heights – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Lamming Mills – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Lang Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Langdale – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Langford – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Langley – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Lantzville – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Larch Hill – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Lardeau – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Larkin – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Larsons Landing – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Lasha – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Lasqueti – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Lasqueti Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Lauretta – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Lavington – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Lawnhill – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Lax Kw''alaams – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Lazo – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Leanchoil – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Lebahdo – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Lee Creek – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Leechtown – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Lees Corner – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Legrand – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Lejac – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Lemon Creek – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Lemoray – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Lempriere – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Leo Creek – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Lexau Ranch – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Liard River – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Liard River 3 – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Liersch – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Lighthouse Point – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Likely – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Lillooet – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Lily Lake – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Lime – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Lincoln Park – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Lindell Beach – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Lindeman – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Line Creek – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Lions Bay – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Lister – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Little Fort – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Little River – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Little Zeballos – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Lockeport – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Log Cabin – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Logan Lake – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Lone Butte – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Lone Prairie – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Long Harbour – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Longbeach – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Longworth – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Loon Lake – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Loon Lake Subdivision – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Loos – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Louis Creek – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Louise Island – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Lower China Creek – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Lower Nicola – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Lower Post – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Lubin – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Lucas – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Lucerne – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Lulu – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Lumberton – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Lumby – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Lund – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Lust Subdivision – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Luxor – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Lyell Island – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Lynx Creek – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Lytton – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Lytton 27B – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Mabel Lake – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Macalister – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Macdonald – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Mackenzie – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Mackin – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'MacNeill – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Madeira Park – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Magic Lake Estates – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Magna Bay – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Magnum Mine – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Mahatta River – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Mahmalillikullah – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Mahood Falls – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Makinson – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Malahat – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Malakwa – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Malcolm Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Malibu – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Mamalilaculla – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Mammel Subdivision – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Manning – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Manning Park – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Manson Creek – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Mansons Landing – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Mapes – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Maple Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Maple Ridge – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Mara – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Marblehead – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Margaret Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Marguerite – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Marigold – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Marilla – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Marktosis – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Marne – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Marron Valley – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Marsh Creek Area – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Martel – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Marten Lake – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Martin Prairie – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Martin Valley – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Martinson – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Marysville – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Mason Creek – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Masset – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Matilpi – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Matsqui Main 2 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Maurelle Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Mayne Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Mayook – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'McAbee – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'McBride – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'McCabe – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'McCall – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'McCalls Landing – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'McConnel – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'McCracken – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'McCulloch – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'McDame – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'McDonalds Landing – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'McGillivray – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'McGregor – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'McGuire – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'McKearney Ranch – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'McKinley Landing – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'McLean Ranch – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'McLeese Lake – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'McLeod – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'McLeod Lake – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'McLeod Subdivision – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'McLure – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'McMillan Island 6 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'McMurdo – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'McMurphy – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'McNab Creek – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Meachen – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Meadow Creek – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Meadows – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Meares Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Meem Quam Leese – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Meldrum – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Meldrum Creek – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Merritt – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Merton – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Merville – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Mesachie Lake – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Messiter – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Metchosin – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Metlakatla – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Meziadin Junction – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Meziadin Subdivision – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Mica Creek – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Middlegate – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Midway – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Mile 19 Overhead – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Mile 422 Alaska Highway – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Mile 62 1/2 – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Mill Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Millers Landing – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Millstream – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Milnes Landing – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Minaty Bay – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Minstrel Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Minto Landing – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Miocene – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Miracle Valley – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Mirror Lake – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Missezula Lake – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Mission – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Mission Island 2 – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Mitchell Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Miworth – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Moberly – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Moberly Lake – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Moffat – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Moha – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Monias – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Mons – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Montague Harbour – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Monte Creek – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Monte Lake – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Montney – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Montrose – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Moose Heights – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Mooyah Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Moran – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Moresby Camp – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Moresby Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Morey – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Moricetown – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Morrissey – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Mount Baldy – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Mount Currie – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Mount Lehman – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Mount Robson – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Mountain Station – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Moyie – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Mud Bay – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Mud River – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Muncho Lake – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Munro – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Munroe – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Murdale – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Musgrave Landing – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Muskwa – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Myra – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Myrtle Point – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Nadu – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Nahmint – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Nahun – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Nakusp – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Nalos Landing – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Namu – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Nanaimo – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Nanoose Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Naramata – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Narcosli Creek – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Nasookin Road Subdivision – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Nass Camp – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Natal – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Nazko – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Nechako – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Nechako Centre – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Nedoats – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Needles – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Needley – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Nelson – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Nelson Forks – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Nelson Island – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Nelway – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Nemiah Valley – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'New Aiyansh – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'New Barkerville – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'New Bella Bella – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'New Brighton – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'New Clew – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'New Denver – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'New Hazelton – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'New Settlement – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'New Westminster – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Newcastle – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Newgate – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Newlands – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Niagara – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Nichol – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Nicholson – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Nicks Island – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Nicola – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Nicomen – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Nig – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Nigei Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Nimpkish – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Nimpkish Heights – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Nimpo Lake – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Ninety Three Mile House – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Ninstints – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Niteal – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Nootka – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Nootka Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Noralee – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Norgate – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Norlake – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'North Bend – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'North Bonaparte – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'North Bulkley – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'North Campbell River – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'North Cowichan – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'North Galiano – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'North Kamloops – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'North Nechako – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'North Pender Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'North Pine – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'North Poplar – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'North Saanich – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'North Star – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'North Vancouver – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Northfield – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Northridge – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Norton – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Notch Hill – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Nuchatlitz – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Nukko Lake – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Nulki – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Nursery – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Oak Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Oak Hills – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Oalthkyim Sechelt Band 4 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Oasis – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Ocean Falls – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Ocean Grove – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'O''Dell – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Ogden – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Okanagan Centre – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Okanagan Falls – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Okanagan Landing – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Okanagan Mission – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'O''Keefe – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Olalla – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Old Bella Bella – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Old Fort – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Old Remo – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Old Town – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Oliver – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Oliver''s Landing – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Olson – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Onward – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Oona River – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Ootischenia – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Ootischenia Flats – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Ootsa Lake – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Opitsat – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Osborn – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Osborn Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Osland – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Osoyoos – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Osprey Lake – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Othello – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Otter Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Ottertail – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Otway – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Oweekeno – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Owen Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Owl Creek – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Oyama – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Oyster River – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Pacific – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Pahas – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Paldi – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Palling – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Palling 1A – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Palliser – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Panorama – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Panorama Subdivision – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Paradise Point – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Paradise Valley – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Park Siding – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Parkland – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Parksville – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Parson – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Pasley Island – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Pass Creek – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Passmore – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Paterson – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Paul Lake – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Paulson – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Pavey – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Pavilion – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Paxton Valley – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Paykulkum Sechelt Band 14 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Peachland – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Peejay – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Pemberton – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Pemberton Heights – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Pemberton Meadows – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Pender Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Pendleton Bay – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Pennington – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Penny – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Penticton – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Perow – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Perrys – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Peterson – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Phelan – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Phillips Arm – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Phoenix – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Piers Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Pilot Bay – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Pinantan Lake – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Pinchi – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Pinchi Lake – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Pine Valley – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Pinegrove – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Pinesul – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Pineview – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Pinewood Subdivision – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Pink Mountain – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Pioneer Mine – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Pitman – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Pitquah – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Pitt Meadows – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Pixie Beach – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Playmor Junction – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Pleasant Camp – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Plumper Harbour – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Point Holmes – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Polley – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Pope Landing – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Popkum – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Poplar Creek – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Poplar Grove – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Porcher Island – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Porpoise Bay – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Port Alberni – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Port Albion – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Port Alice – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Port Clements – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Port Coquitlam – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Port Desire – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Port Douglas – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Port Edward – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Port Essington – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Port Hammond – Haney – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Port Hardy – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Port Kells – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Port McNeill – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Port Mellon – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Port Moody – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Port Neville – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Port Renfrew – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Port Simpson 1 – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Port Washington – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Porteau – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Porteous – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Porter Landing – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Portland Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Porto Rico – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Poser – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Postill – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Potter – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Pouce Coupe – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Poupore – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Powell River – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Powers Addition – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Prairie Valley – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Premier – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Premier Lake – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Prespatou – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Pressy Lake – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Prince George – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Prince Rupert – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Princeton – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Pritchard – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Procter – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Progress – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Promontory – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Prophet River – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Prospect Lake – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Protection Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Punchaw – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Puntledge – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Purden Lake – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Pyramid – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Quadra Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Qualicum Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Qualicum Beach – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Quamichan – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Quathiaski Cove – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Quatsino – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Quaw – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Queen Charlotte City – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Queens Bay – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Queens Cove – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Quesnel – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Quesnel Canyon – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Quesnel Forks – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Quesnel View – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Quick – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Quilchena – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Quinsam – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Radium – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Radium Hot Springs – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Raft River – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Rail Lake – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Rainy Hollow – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Ranchero – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Raspberry – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Raush Valley – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Rayleigh – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Read Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Reclaim – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Red Bluff – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Red Mountain – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Red Pass – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Red Rock – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Red Rose – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Redgrave – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Redroofs – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Redstone – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Refuge Cove – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Reid Lake – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Remac – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Remo – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Renata – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Retallack – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Retaskit – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Revelstoke – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Rhone – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Rich Bar – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Richmond – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Rider – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Ridgedale – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Ridley – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Riley – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Riondel – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Riske Creek – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Ritchie – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'River Jordan – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'River Springs – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Rivers Inlet – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Riverside – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Rivervale – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Roberts Creek – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Robin Creek – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Robson – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Robson West – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Rock Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Rock Creek – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Rockyview – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Roe Lake – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Rogers – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Rogers Pass – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Rolla – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Rolling Hills Park – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Roosville – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Rose Harbour – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Rose Lake – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Rose Prairie – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Rosebery – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Rosedale – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Ross Peak – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Ross Spur – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Rossland – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Rosswood – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Round Lake – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Round Prairie – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Roy – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Royston – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Ruby Creek – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Rumble Beach – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Rupert – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Rushmere – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Rutland – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Ryan – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Ryder Lake – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Rykerts – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Saanich – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Saanichton – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Saddle Rock – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Sahali – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Sahara Heights – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Sahtlam – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Sallahlus Sechelt Band 20 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Sallahlus Sechelt Band 20A – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Salmo – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Salmon Arm – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Salmon Valley – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Saloon – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Salt Spring Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Saltair – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Saltery Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Salvus – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Samuel Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'San Josef – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Sanca – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Sanderson Site – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Sandon – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Sandspit – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Sandwick – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Sandy Point – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Saratoga Beach – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Sardis – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Sarita – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Saseenos – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Saturna Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Saughanaught Sechelt Band 22 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Savary Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Savona – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Savory – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Sawquamain Sechelt Band 19A – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Sayward – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Scotch Creek – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Scotia Bay – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Scott Cove – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Scotty Creek – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Seaford – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Seal Bay Subdivision – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Seaside Park – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Sechelt – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Sechelt Indian Government District – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Sechelt Sechelt Band 2 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Secret Cove – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Seddall – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Seeney – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Sekaleton Sechelt Band 21 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Sekaleton Sechelt Band 21A – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Selma Park – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Semlin – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Septimus – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Seton – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Seton Portage – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Seven Mile Corner – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Seventy Mile House – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Sewall – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Sewell Inlet – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Seymour Arm – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Seymour Inlet – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Seymour Lake – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Shady Valley – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Shalalth – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Shames – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Shannon – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Shannon Bay – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Shannon Creek Sechelt Band 28 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Shawl Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Shawnigan Lake – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Shearer Dale – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Shearwater – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Shelley – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Shelter Bay – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Shelter Point – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Sheraton – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Shere – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Sheridan Lake – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Sheslay – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Shingle Creek – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Shirley – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Shoreacres – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Shoreholme – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Shulus – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Shushartie – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Shuswap – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Shuswap Falls – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Shutty Bench – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Sicamous – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Sidley – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Sidney – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Sikanni – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Sikanni Chief – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Silica – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Silver Creek – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Silver Lake – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Silver River – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Silverdale – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Silverhill – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Silverton – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Simpson Ranch – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Sinclair Mills – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Sinkut River – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Sirdar – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Six Mile Point – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Skedans – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Skeena – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Skeena Crossing – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Skidegate – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Skidegate Landing – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Skooks Landing – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Skookumchuck – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Skookumchuck Sechelt Band 27 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Skoonka – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Skwawkweehm Sechelt Band 17 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Skweahm 10 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Slaterville – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Slayathlum Sechelt Band 16 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Slesse Park – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Sliammon – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Slocan – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Slocan Park – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Smeshalin Sechelt Band 18 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Smith River – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Smithers – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Smithers Landing – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Snake 5 – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Snake River – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Snyder – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Soames Point – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Sockeye – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Soda Creek – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Sointula – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Solly – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Solsqua – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Somenos – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Sonora Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Sooke – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Sorrento – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'South Bentinck – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'South Canoe – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'South Dawson – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'South Fort George – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'South Hazelton – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'South Lakeside – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'South Lakeside (Williams Lake) – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'South Pender Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'South Poplar – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'South Shalalth – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'South Slocan – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'South Slope – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'South Sumas – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'South Taylor – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'South Thormanby Island – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'South Wellington – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Southbank – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Soyandostar 2 – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Spallumcheen – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Sparwood – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Spatsum – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Spences Bridge – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Sperling – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Spicer – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Spillamacheen – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Springfield Ranch – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Springhouse – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Sproat Lake – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Sproatt – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Sproule Creek – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Spur Valley Subdivision – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Spuzzum – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Squamish – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Squawkum Creek 3 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Squeah – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Squilax – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Squirrel Cove – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'St. Andrews – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'St. Eugene Mission – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'St. Ives – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'St. Joseph Mission – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'St. Mary Lake – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'St. Vincent Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Stanley – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Star Subdivision – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Starks – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Stave Falls – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Steamboat – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Steelhead – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Stellako – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Stephen – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Stepping Stones Estates – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Stewardson Inlet – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Stewart – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Stikine – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Still Creek – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Stillwater – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Stockett – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Stoner – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Stones Bay – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Stoney Creek – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Stories Beach – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Stout – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Straiton – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Strathcona Lodge – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Strathnaver – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Streatham – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Stuart Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Stuart River – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Stuie – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Stump Lake – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Sturdies Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Suahbin Sechelt Band 19 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Sugarcane – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Sullivan Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Summerland – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Summit Lake – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Sun Peaks – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Sundance – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Sundance Subdivision – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Sunningdale – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Sunnybrae – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Sunnyside – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Sunrise Valley – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Sunset Beach – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Sunset Prairie – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Sunshine Bay – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Sunshine Valley – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Suquash – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Surge Narrows – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Surprise – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Surrey – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Swansea – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Swartz Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Swaycalse Sechelt Band 3 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Swaywelat Sechelt Band 12 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Sweetsbridge – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Sweetwater – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Swift – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Swiftwater – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Sydney Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Ta Ta Creek – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Tabor – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Tacheeda – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Tachie – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Tadanac – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Taft – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Taghum – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Tahltan – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Tahsis – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Takla Landing – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Taku – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Takysie Lake – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Tallheo – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Tamarack – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Tamarisk – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Tantalus Acres – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Tanu – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Tappen – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Tarrys – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Tasu – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Tatalrose – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Tatla Lake – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Tatlow – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Tatogga – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Tatton – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Taverna – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Taylor – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Tchahchelailthtenum Sechelt Band 10 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Tchesinkut Lake – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Teakerne Arm – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Teko – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Telachick – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Telegraph Cove – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Telegraph Creek – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Telkwa – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Ten Mile Lake – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Terrace – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Tete Jaune – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Tete Jaune Cache – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Texada Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Theodosia Arm – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Thetis Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Thompson – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Thompson River Estates – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Thompson Sound – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Thornhill – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Three Forks – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Three Valley – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Thrums – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Thunder River – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Thunderbird – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Thurlow – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Thurston Harbour – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Tibbets – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Tiilis Landing – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Tillicum – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Tintagel – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Tipella – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Tisdall – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Tlell – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Toad River – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Toby Creek – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Tochty – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Tofino – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Toketic – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Tomslake – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Topley – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Torrent – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Towdystan – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Tower Lake – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Townsend – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Tracard – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Traders Cove – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Trafalgar – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Trail – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Tranquille – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Tremblay – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Trembleur – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Trepanier – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Trevor Channel – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Trinity Valley – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Troup – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Trout Creek – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Trout Lake – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Trutch – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Tsawcome Sechelt Band 1 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Tsawwassen Beach – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Tsay Keh Dene – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Tsimpsean 2 North Part – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Tsolum River – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Tsooahdie Sechelt Band 15 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Tulameen – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Tulsequah – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Tumbler Ridge – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Tupper – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Turner Subdivision – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Turtle Valley – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Tuwanek – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Twidwell Bend – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Twin Bays – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Twin Butte – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Twin Creeks – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Twin Islands – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Two Mile – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Two Mile Hazelton – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Two Rivers – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Tye – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Tyee – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Tzouhalem – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Tzuhalem – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Ucluelet – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Ulkatcho – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Union Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Upper Bench – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Upper China Creek – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Upper Cutbank – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Upper Fraser – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Upper Halfway – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Upper Sumas 6 – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Urling – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Urquhart – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Usk – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Valdes Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Valemount – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Valhalla – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Valley View – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Valleycliffe – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Valleyview – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Vallican – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Van Anda – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Vancouver – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Vanderhoof – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Vanway – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Vargas Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Vaseaux Lake – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Vaucroft Beach – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Vavenby – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Vedder Crossing – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Vermilion Crossing – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Vernon – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Vesuvius – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Victoria – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Victoria Lake – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Vidette – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'View Royal – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Vinsulla – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Von Zuben – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Vye – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Wabi – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Wabron – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Wadhams – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)