PRINT 'ADD COMMUNITIES 2001 - 2119'

INSERT [dbo].[Communities] ([Caption], [IsActive], [RowSequence], [DateAdded], [DateUpdated])
VALUES
(N'Waglisla – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Wagner Ranch – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Wakely – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Walcott – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Walhachin – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Walker – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Walkers – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Wall Beach – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Waneta – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Wanklyn – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Wardner – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Ware – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Warfield – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Warner Bay – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Wasa – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Wasa Lake – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Watson – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Watson Island – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Websters Corners – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Wedeene – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Wedge – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Wedgwood – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Weewanie – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Welcome Beach – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Wellington – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Wells – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Weneez – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'West Bench – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'West Fernie – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'West Heights – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'West Kelowna – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'West Landing – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'West Mara Lake – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'West Midway – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'West Sechelt – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'West Thurlow Island – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'West Trail – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'West Vancouver – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Westbank – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Westbridge – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Westholme – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Westley – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Westply – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Westside – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Westsyde – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Westview – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Westwold – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Whaletown – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Whiplash Ranch – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Whisky Creek – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Whistler – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Whistler Creek – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'White Lake – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'White Pass – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'White Rock – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Whitecroft – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Whonnock – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Whyac – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Wildwood – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Wildwood Subdivision – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Wiley – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Williams Beach – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Williams Lake – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Williams Landing – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Williamsons Landing – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Willow Brook – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Willow Flats – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Willow Point – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Willow Ranch – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Willow River – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Willow Valley – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Willowbrook – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Willowvale – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Wilmer – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Wilson Creek – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Wilson Landing – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Windermere – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Windy – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Winfield – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Wingdam – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Winlaw – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Winter Harbour – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Wistaria – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Wolf – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Wolfenden – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Wolverine – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Wonowon – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Woodcock – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Woodfibre – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Woodmere – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Woodpecker – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Woods Landing – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Woodsdale – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Worth – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Woss – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Wright – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Wycliffe – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Wyman – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Wynndel – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Yaculta – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Yahk – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Yaku – North Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Yale – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Yankee Flats – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Yarksis – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Yarrow – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Yekooche – Nechako', 1, 0, GETUTCDATE(), NULL)
,(N'Yellow Point – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Yellowhead – Cariboo', 1, 0, GETUTCDATE(), NULL)
,(N'Yennadon – Mainland/Southwest', 1, 0, GETUTCDATE(), NULL)
,(N'Ymir – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Yoho – Thompson Okanagan', 1, 0, GETUTCDATE(), NULL)
,(N'Youbou – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Yreka – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Yuquot – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Zamora – Kootenay', 1, 0, GETUTCDATE(), NULL)
,(N'Zeballos – Vancouver Island/Coast', 1, 0, GETUTCDATE(), NULL)
,(N'Zeke – Northeast', 1, 0, GETUTCDATE(), NULL)
,(N'Zincton – Kootenay', 1, 0, GETUTCDATE(), NULL)