PRINT 'INSERT [GrantStreams]'

INSERT [dbo].[GrantStreams] (
	[Name]
	, [GrantProgramId]
	, [AccountCodeId]
	, [ProgramConfigurationId]
	, [Objective]
	, [MaxReimbursementAmt]
	, [ReimbursementRate]
	, [AttachmentsIsEnabled]
	, [AttachmentsHeader]
	, [AttachmentsUserGuidance]
	, [AttachmentsMaximum]
	, [AttachmentsRequired]
	, [EligibilityRequirements]
	, [EligibilityEnabled]
	, [EligibilityQuestion]
	, [EligibilityRequired]
	, [IsActive]
	, [IncludeDeliveryPartner]
	, [CanReportParticipants]
	, [DateFirstUsed]
	, [DefaultDeniedRate]
	, [DefaultWithdrawnRate]
	, [DefaultReductionRate]
	, [DefaultSlippageRate]
	, [DefaultCancellationRate]
	, [DateAdded]
	, [DateUpdated]
) 
VALUES (
	N'Emerging Priorities' -- [Name]
	, 3 -- [GrantProgramId]
	, 3 -- [AccountCodeId]
	, 2 -- [ProgramConfigurationId]
	, N'<a href="https://www.workbc.ca/Employment-Services/Community-Workforce-Response-Grant/Emerging-Priorities.aspx">The Emerging Priorities stream</a> supports communities undergoing a significant shift in the local labour market. Some reasons for the shift may be an industry closure or expansion, a natural disaster such as a forest fire or a flood, or other conditions that have impacted employment in the community.'
	, 15000 -- [MaxReimbursementAmt]
	, 1 -- [ReimbursementRate]
	, 1 -- [AttachmentsIsEnabled]
	, N'Detailed Program Description and Letters of Support' -- [AttachmentsHeader]
	, N'SAM TO PROVIDE TEXT' -- [AttachmentsUserGuidance]
	, 10 -- [AttachmentsMaximum]
	, 1 -- [AttachmentsRequired]
	, N'The Emerging Priorities Stream supports communities undergoing a significant shift in the local labour market. Some reasons for the shift may be an industry closure or expansion, a natural disaster such as a forest fire or a flood, or other conditions that have impacted employment in the community.'  -- [EligibilityRequirements]
	, 1 -- [EligibilityEnabled]
	, N'Will the proposed program train and employ people affected by urgent labour market challenge or opportunity?' -- [EligibilityQuestion]
	, 1 -- [EligibilityRequired]
	, 1 -- [IsActive]
	, 0 -- [IncludeDeliveryPartner]
	, 0 -- [CanReportParticipants]
	, NULL -- [DateFirstUsed]
	, 0 -- [DefaultDeniedRate]
	, 0 -- [DefaultWithdrawnRate]
	, 0 -- [DefaultReductionRate]
	, 0 -- [DefaultSlippageRate]
	, 0 -- [DefaultCancellationRate]
	, GETUTCDATE() -- [DateAdded]
	, NULL -- [DateUpdated]
)
,(
	N'Indigenous Communities' -- [Name]
	, 3 -- [GrantProgramId]
	, 3 -- [AccountCodeId]
	, 2 -- [ProgramConfigurationId]
	, N'<a href="https://www.workbc.ca/Employment-Services/Community-Workforce-Response-Grant/Indigenous-Communities.aspx">The Indigenous Communities Stream</a> provides funding to Indigenous communities so they can develop the skills their people need for employment or self-employment.'
	, 15000 -- [MaxReimbursementAmt]
	, 1 -- [ReimbursementRate]
	, 1 -- [AttachmentsIsEnabled]
	, N'Detailed Program Description and Letters of Support' -- [AttachmentsHeader]
	, N'SAM TO PROVIDE TEXT' -- [AttachmentsUserGuidance]
	, 10 -- [AttachmentsMaximum]
	, 1 -- [AttachmentsRequired]
	, N'The Indigenous Communities Stream provides funding to Indigenous communities so they can develop the skills their people need for employment or self-employment.'  -- [EligibilityRequirements]
	, 1 -- [EligibilityEnabled]
	, N'Will the proposed program provide the skills indigenous people need for employment or self-employment?' -- [EligibilityQuestion]
	, 1 -- [EligibilityRequired]
	, 1 -- [IsActive]
	, 0 -- [IncludeDeliveryPartner]
	, 0 -- [CanReportParticipants]
	, NULL -- [DateFirstUsed]
	, 0 -- [DefaultDeniedRate]
	, 0 -- [DefaultWithdrawnRate]
	, 0 -- [DefaultReductionRate]
	, 0 -- [DefaultSlippageRate]
	, 0 -- [DefaultCancellationRate]
	, GETUTCDATE() -- [DateAdded]
	, NULL -- [DateUpdated]
)
,(
	N'Workforce Shortages' -- [Name]
	, 3 -- [GrantProgramId]
	, 3 -- [AccountCodeId]
	, 2 -- [ProgramConfigurationId]
	, N'<a href="https://www.workbc.ca/Employment-Services/Community-Workforce-Response-Grant/Workforce-Shortages.aspx">The Workforce Shortages Stream</a> supports sectors and industries in addressing immediate workforce shortages within the in-demand occupations'
	, 15000 -- [MaxReimbursementAmt]
	, 1 -- [ReimbursementRate]
	, 1 -- [AttachmentsIsEnabled]
	, N'Detailed Program Description and Letters of Support' -- [AttachmentsHeader]
	, N'SAM TO PROVIDE TEXT' -- [AttachmentsUserGuidance]
	, 10 -- [AttachmentsMaximum]
	, 1 -- [AttachmentsRequired]
	, N'The Workforce Shortages Stream supports sectors and industries in addressing immediate workforce shortages within the in-demand occupations.'  -- [EligibilityRequirements]
	, 1 -- [EligibilityEnabled]
	, N'Will the proposed program provide skills and employ people in the in-demand occupations and in the industries experiencing significant workforce shortages?' -- [EligibilityQuestion]
	, 1 -- [EligibilityRequired]
	, 1 -- [IsActive]
	, 0 -- [IncludeDeliveryPartner]
	, 0 -- [CanReportParticipants]
	, NULL -- [DateFirstUsed]
	, 0 -- [DefaultDeniedRate]
	, 0 -- [DefaultWithdrawnRate]
	, 0 -- [DefaultReductionRate]
	, 0 -- [DefaultSlippageRate]
	, 0 -- [DefaultCancellationRate]
	, GETUTCDATE() -- [DateAdded]
	, NULL -- [DateUpdated]
)