PRINT 'Start Insert of Industries'

PRINT ' - Deleting Industries'

DELETE FROM PrioritizationIndustryScores
GO

PRINT ' - Inserting Industries'

INSERT INTO PrioritizationIndustryScores (Name, NaicsCode, IndustryScore, DateAdded)
VALUES
('Farms and support activities', '1111', 3, GETUTCDATE()), 
('Farms and support activities', '1112', 3, GETUTCDATE()), 
('Farms and support activities', '1113', 3, GETUTCDATE()), 
('Farms and support activities', '1114', 3, GETUTCDATE()), 
('Farms and support activities', '1119', 3, GETUTCDATE()), 
('Farms and support activities', '1121', 3, GETUTCDATE()), 
('Farms and support activities', '1122', 3, GETUTCDATE()), 
('Farms and support activities', '1123', 3, GETUTCDATE()), 
('Farms and support activities', '1124', 3, GETUTCDATE()), 
('Farms and support activities', '1125', 3, GETUTCDATE()), 
('Farms and support activities', '1129', 3, GETUTCDATE()), 
('Forestry, logging and support activities', '1131', 2, GETUTCDATE()), 
('Forestry, logging and support activities', '1132', 2, GETUTCDATE()), 
('Forestry, logging and support activities', '1133', 2, GETUTCDATE()), 
('Fishing, hunting and trapping', '1141', 4, GETUTCDATE()), 
('Fishing, hunting and trapping', '1142', 4, GETUTCDATE()), 
('Farms and support activities', '1151', 3, GETUTCDATE()), 
('Farms and support activities', '1152', 3, GETUTCDATE()), 
('Forestry, logging and support activities', '1153', 2, GETUTCDATE()), 
('Oil and gas extraction', '2111', 1, GETUTCDATE()), 
('Mining', '2121', 2, GETUTCDATE()), 
('Mining', '2122', 2, GETUTCDATE()), 
('Mining', '2123', 2, GETUTCDATE()), 
('Support activities for mining and oil and gas extraction', '2131', 1, GETUTCDATE()), 
('Utilities', '2211', 3, GETUTCDATE()), 
('Utilities', '2212', 3, GETUTCDATE()), 
('Utilities', '2213', 3, GETUTCDATE()), 
('Residential building construction', '2361', 1, GETUTCDATE()), 
('Non-residential building construction', '2362', 2, GETUTCDATE()), 
('Heavy and civil engineering construction', '2371', 2, GETUTCDATE()), 
('Heavy and civil engineering construction', '2372', 2, GETUTCDATE()), 
('Heavy and civil engineering construction', '2373', 2, GETUTCDATE()), 
('Heavy and civil engineering construction', '2379', 2, GETUTCDATE()), 
('Specialty trade contractors', '2381', 3, GETUTCDATE()), 
('Specialty trade contractors', '2382', 3, GETUTCDATE()), 
('Specialty trade contractors', '2383', 3, GETUTCDATE()), 
('Specialty trade contractors', '2389', 3, GETUTCDATE()), 
('Food, beverage and tobacco manufacturing', '3111', 3, GETUTCDATE()), 
('Food, beverage and tobacco manufacturing', '3112', 3, GETUTCDATE()), 
('Food, beverage and tobacco manufacturing', '3113', 3, GETUTCDATE()), 
('Food, beverage and tobacco manufacturing', '3114', 3, GETUTCDATE()), 
('Food, beverage and tobacco manufacturing', '3115', 3, GETUTCDATE()), 
('Food, beverage and tobacco manufacturing', '3116', 3, GETUTCDATE()), 
('Food, beverage and tobacco manufacturing', '3117', 3, GETUTCDATE()), 
('Food, beverage and tobacco manufacturing', '3118', 3, GETUTCDATE()), 
('Food, beverage and tobacco manufacturing', '3119', 3, GETUTCDATE()), 
('Food, beverage and tobacco manufacturing', '3121', 3, GETUTCDATE()), 
('Food, beverage and tobacco manufacturing', '3122', 3, GETUTCDATE()), 
('Food, beverage and tobacco manufacturing', '3123', 3, GETUTCDATE()), 
('Other manufacturing', '3131', 3, GETUTCDATE()), 
('Other manufacturing', '3132', 3, GETUTCDATE()), 
('Other manufacturing', '3133', 3, GETUTCDATE()), 
('Other manufacturing', '3141', 3, GETUTCDATE()), 
('Other manufacturing', '3149', 3, GETUTCDATE()), 
('Other manufacturing', '3151', 3, GETUTCDATE()), 
('Other manufacturing', '3152', 3, GETUTCDATE()), 
('Other manufacturing', '3159', 3, GETUTCDATE()), 
('Other manufacturing', '3161', 3, GETUTCDATE()), 
('Other manufacturing', '3162', 3, GETUTCDATE()), 
('Other manufacturing', '3169', 3, GETUTCDATE()), 
('Wood product manufacturing', '3211', 2, GETUTCDATE()), 
('Wood product manufacturing', '3212', 2, GETUTCDATE()), 
('Wood product manufacturing', '3219', 2, GETUTCDATE()), 
('Paper manufacturing', '3221', 2, GETUTCDATE()), 
('Paper manufacturing', '3222', 2, GETUTCDATE()), 
('Other manufacturing', '3231', 3, GETUTCDATE()), 
('Other manufacturing', '3241', 3, GETUTCDATE()), 
('Other manufacturing', '3251', 3, GETUTCDATE()), 
('Other manufacturing', '3252', 3, GETUTCDATE()), 
('Other manufacturing', '3253', 3, GETUTCDATE()), 
('Other manufacturing', '3254', 3, GETUTCDATE()), 
('Other manufacturing', '3255', 3, GETUTCDATE()), 
('Other manufacturing', '3256', 3, GETUTCDATE()), 
('Other manufacturing', '3259', 3, GETUTCDATE()), 
('Other manufacturing', '3261', 3, GETUTCDATE()), 
('Other manufacturing', '3262', 3, GETUTCDATE()), 
('Other manufacturing', '3271', 3, GETUTCDATE()), 
('Other manufacturing', '3272', 3, GETUTCDATE()), 
('Other manufacturing', '3273', 3, GETUTCDATE()), 
('Other manufacturing', '3274', 3, GETUTCDATE()), 
('Other manufacturing', '3279', 3, GETUTCDATE()), 
('Primary metal manufacturing', '3311', 3, GETUTCDATE()), 
('Primary metal manufacturing', '3312', 3, GETUTCDATE()), 
('Primary metal manufacturing', '3313', 3, GETUTCDATE()), 
('Primary metal manufacturing', '3314', 3, GETUTCDATE()), 
('Primary metal manufacturing', '3315', 3, GETUTCDATE()), 
('Fabricated metal product manufacturing', '3321', 2, GETUTCDATE()), 
('Fabricated metal product manufacturing', '3322', 2, GETUTCDATE()), 
('Fabricated metal product manufacturing', '3323', 2, GETUTCDATE()), 
('Fabricated metal product manufacturing', '3324', 2, GETUTCDATE()), 
('Fabricated metal product manufacturing', '3325', 2, GETUTCDATE()), 
('Fabricated metal product manufacturing', '3326', 2, GETUTCDATE()), 
('Fabricated metal product manufacturing', '3327', 2, GETUTCDATE()), 
('Fabricated metal product manufacturing', '3328', 2, GETUTCDATE()), 
('Fabricated metal product manufacturing', '3329', 2, GETUTCDATE()), 
('Machinery manufacturing', '3331', 2, GETUTCDATE()), 
('Machinery manufacturing', '3332', 2, GETUTCDATE()), 
('Machinery manufacturing', '3333', 2, GETUTCDATE()), 
('Machinery manufacturing', '3334', 2, GETUTCDATE()), 
('Machinery manufacturing', '3335', 2, GETUTCDATE()), 
('Machinery manufacturing', '3336', 2, GETUTCDATE()), 
('Machinery manufacturing', '3339', 2, GETUTCDATE()), 
('Other manufacturing', '3341', 3, GETUTCDATE()), 
('Other manufacturing', '3342', 3, GETUTCDATE()), 
('Other manufacturing', '3343', 3, GETUTCDATE()), 
('Other manufacturing', '3344', 3, GETUTCDATE()), 
('Other manufacturing', '3345', 3, GETUTCDATE()), 
('Other manufacturing', '3346', 3, GETUTCDATE()), 
('Other manufacturing', '3351', 3, GETUTCDATE()), 
('Other manufacturing', '3352', 3, GETUTCDATE()), 
('Other manufacturing', '3353', 3, GETUTCDATE()), 
('Other manufacturing', '3359', 3, GETUTCDATE()), 
('Transportation equipment manufacturing (excluding shipbuilding)', '3361', 2, GETUTCDATE()), 
('Transportation equipment manufacturing (excluding shipbuilding)', '3362', 2, GETUTCDATE()), 
('Transportation equipment manufacturing (excluding shipbuilding)', '3363', 2, GETUTCDATE()), 
('Transportation equipment manufacturing (excluding shipbuilding)', '3364', 2, GETUTCDATE()), 
('Transportation equipment manufacturing (excluding shipbuilding)', '3365', 2, GETUTCDATE()), 
('Ship and boat building', '3366', 2, GETUTCDATE()), 
('Transportation equipment manufacturing (excluding shipbuilding)', '3369', 2, GETUTCDATE()), 
('Other manufacturing', '3371', 2, GETUTCDATE()), 
('Other manufacturing', '3372', 3, GETUTCDATE()), 
('Other manufacturing', '3379', 3, GETUTCDATE()), 
('Other manufacturing', '3391', 3, GETUTCDATE()), 
('Other manufacturing', '3399', 3, GETUTCDATE()), 
('Wholesale trade', '4111', 2, GETUTCDATE()), 
('Wholesale trade', '4121', 2, GETUTCDATE()), 
('Wholesale trade', '4131', 2, GETUTCDATE()), 
('Wholesale trade', '4132', 2, GETUTCDATE()), 
('Wholesale trade', '4133', 2, GETUTCDATE()), 
('Wholesale trade', '4134', 2, GETUTCDATE()), 
('Wholesale trade', '4141', 2, GETUTCDATE()), 
('Wholesale trade', '4142', 2, GETUTCDATE()), 
('Wholesale trade', '4143', 2, GETUTCDATE()), 
('Wholesale trade', '4144', 2, GETUTCDATE()), 
('Wholesale trade', '4145', 2, GETUTCDATE()), 
('Wholesale trade', '4151', 2, GETUTCDATE()), 
('Wholesale trade', '4152', 2, GETUTCDATE()), 
('Wholesale trade', '4153', 2, GETUTCDATE()), 
('Wholesale trade', '4161', 2, GETUTCDATE()), 
('Wholesale trade', '4162', 2, GETUTCDATE()), 
('Wholesale trade', '4163', 2, GETUTCDATE()), 
('Wholesale trade', '4171', 2, GETUTCDATE()), 
('Wholesale trade', '4172', 2, GETUTCDATE()), 
('Wholesale trade', '4173', 2, GETUTCDATE()), 
('Wholesale trade', '4179', 2, GETUTCDATE()), 
('Wholesale trade', '4181', 2, GETUTCDATE()), 
('Wholesale trade', '4182', 2, GETUTCDATE()), 
('Wholesale trade', '4183', 2, GETUTCDATE()), 
('Wholesale trade', '4184', 2, GETUTCDATE()), 
('Wholesale trade', '4189', 2, GETUTCDATE()), 
('Wholesale trade', '4191', 2, GETUTCDATE()), 
('Motor vehicle and parts dealers', '4411', 2, GETUTCDATE()), 
('Motor vehicle and parts dealers', '4412', 2, GETUTCDATE()), 
('Motor vehicle and parts dealers', '4413', 2, GETUTCDATE()), 
('Other retail trade (excluding cars, online shopping and personal care)', '4421', 3, GETUTCDATE()), 
('Other retail trade (excluding cars, online shopping and personal care)', '4422', 3, GETUTCDATE()), 
('Other retail trade (excluding cars, online shopping and personal care)', '4431', 3, GETUTCDATE()), 
('Other retail trade (excluding cars, online shopping and personal care)', '4441', 3, GETUTCDATE()), 
('Other retail trade (excluding cars, online shopping and personal care)', '4442', 3, GETUTCDATE()), 
('Other retail trade (excluding cars, online shopping and personal care)', '4451', 3, GETUTCDATE()), 
('Other retail trade (excluding cars, online shopping and personal care)', '4452', 3, GETUTCDATE()), 
('Other retail trade (excluding cars, online shopping and personal care)', '4453', 3, GETUTCDATE()), 
('Health and personal care stores', '4461', 3, GETUTCDATE()), 
('Other retail trade (excluding cars, online shopping and personal care)', '4471', 3, GETUTCDATE()), 
('Other retail trade (excluding cars, online shopping and personal care)', '4481', 3, GETUTCDATE()), 
('Other retail trade (excluding cars, online shopping and personal care)', '4482', 3, GETUTCDATE()), 
('Other retail trade (excluding cars, online shopping and personal care)', '4483', 3, GETUTCDATE()), 
('Other retail trade (excluding cars, online shopping and personal care)', '4511', 3, GETUTCDATE()), 
('Other retail trade (excluding cars, online shopping and personal care)', '4513', 3, GETUTCDATE()), 
('Other retail trade (excluding cars, online shopping and personal care)', '4521', 3, GETUTCDATE()), 
('Other retail trade (excluding cars, online shopping and personal care)', '4529', 3, GETUTCDATE()), 
('Other retail trade (excluding cars, online shopping and personal care)', '4531', 3, GETUTCDATE()), 
('Other retail trade (excluding cars, online shopping and personal care)', '4532', 3, GETUTCDATE()), 
('Other retail trade (excluding cars, online shopping and personal care)', '4533', 3, GETUTCDATE()), 
('Other retail trade (excluding cars, online shopping and personal care)', '4539', 3, GETUTCDATE()), 
('Online shopping', '4541', 2, GETUTCDATE()), 
('Other retail trade (excluding cars, online shopping and personal care)', '4542', 3, GETUTCDATE()), 
('Other retail trade (excluding cars, online shopping and personal care)', '4543', 3, GETUTCDATE()), 
('Air transportation and support activities', '4811', 2, GETUTCDATE()), 
('Air transportation and support activities', '4812', 2, GETUTCDATE()), 
('Rail transportation and support activities', '4821', 2, GETUTCDATE()), 
('Water transportation', '4831', 1, GETUTCDATE()), 
('Water transportation', '4832', 1, GETUTCDATE()), 
('Truck transportation and support activities', '4841', 2, GETUTCDATE()), 
('Truck transportation and support activities', '4842', 2, GETUTCDATE()), 
('Transit, sightseeing and pipeline transportation', '4851', 2, GETUTCDATE()), 
('Transit, sightseeing and pipeline transportation', '4852', 2, GETUTCDATE()), 
('Transit, sightseeing and pipeline transportation', '4853', 2, GETUTCDATE()), 
('Transit, sightseeing and pipeline transportation', '4854', 2, GETUTCDATE()), 
('Transit, sightseeing and pipeline transportation', '4855', 2, GETUTCDATE()), 
('Transit, sightseeing and pipeline transportation', '4859', 2, GETUTCDATE()), 
('Transit, sightseeing and pipeline transportation', '4861', 2, GETUTCDATE()), 
('Transit, sightseeing and pipeline transportation', '4862', 2, GETUTCDATE()), 
('Transit, sightseeing and pipeline transportation', '4869', 2, GETUTCDATE()), 
('Transit, sightseeing and pipeline transportation', '4871', 2, GETUTCDATE()), 
('Transit, sightseeing and pipeline transportation', '4872', 2, GETUTCDATE()), 
('Transit, sightseeing and pipeline transportation', '4879', 2, GETUTCDATE()), 
('Air transportation and support activities', '4881', 2, GETUTCDATE()), 
('Rail transportation and support activities', '4882', 2, GETUTCDATE()), 
('Ports and freight transportation arrangement', '4883', 1, GETUTCDATE()), 
('Truck transportation and support activities', '4884', 2, GETUTCDATE()), 
('Ports and freight transportation arrangement', '4885', 1, GETUTCDATE()), 
('Ports and freight transportation arrangement', '4889', 1, GETUTCDATE()), 
('Postal service, couriers and messengers', '4911', 2, GETUTCDATE()), 
('Postal service, couriers and messengers', '4921', 2, GETUTCDATE()), 
('Postal service, couriers and messengers', '4922', 2, GETUTCDATE()), 
('Warehousing and storage', '4931', 3, GETUTCDATE()), 
('Publishing industries', '5111', 3, GETUTCDATE()), 
('Publishing industries', '5112', 3, GETUTCDATE()), 
('Motion picture and sound recording industries', '5121', 2, GETUTCDATE()), 
('Motion picture and sound recording industries', '5122', 2, GETUTCDATE()), 
('Broadcasting, data processing and information', '5151', 2, GETUTCDATE()), 
('Broadcasting, data processing and information', '5152', 2, GETUTCDATE()), 
('Telecommunications', '5173', 3, GETUTCDATE()), 
('Telecommunications', '5174', 3, GETUTCDATE()), 
('Telecommunications', '5179', 3, GETUTCDATE()), 
('Broadcasting, data processing and information', '5182', 2, GETUTCDATE()), 
('Broadcasting, data processing and information', '5191', 2, GETUTCDATE()), 
('Finance', '5211', 3, GETUTCDATE()), 
('Finance', '5221', 3, GETUTCDATE()), 
('Finance', '5222', 3, GETUTCDATE()), 
('Finance', '5223', 3, GETUTCDATE()), 
('Finance', '5231', 3, GETUTCDATE()), 
('Finance', '5232', 3, GETUTCDATE()), 
('Finance', '5239', 3, GETUTCDATE()), 
('Insurance carriers and related activities', '5241', 3, GETUTCDATE()), 
('Insurance carriers and related activities', '5242', 3, GETUTCDATE()), 
('Finance', '5261', 3, GETUTCDATE()), 
('Finance', '5269', 3, GETUTCDATE()), 
('Real estate and rental and leasing', '5311', 2, GETUTCDATE()), 
('Real estate and rental and leasing', '5312', 2, GETUTCDATE()), 
('Real estate and rental and leasing', '5313', 2, GETUTCDATE()), 
('Real estate and rental and leasing', '5321', 2, GETUTCDATE()), 
('Real estate and rental and leasing', '5322', 2, GETUTCDATE()), 
('Real estate and rental and leasing', '5323', 2, GETUTCDATE()), 
('Real estate and rental and leasing', '5324', 2, GETUTCDATE()), 
('Real estate and rental and leasing', '5331', 2, GETUTCDATE()), 
('Legal, accounting, design, research and advertising services', '5411', 2, GETUTCDATE()), 
('Legal, accounting, design, research and advertising services', '5412', 2, GETUTCDATE()), 
('Architectural, engineering and related services', '5413', 2, GETUTCDATE()), 
('Legal, accounting, design, research and advertising services', '5414', 2, GETUTCDATE()), 
('Computer systems design and related services', '5415', 2, GETUTCDATE()), 
('Management, scientific and technical consulting services', '5416', 2, GETUTCDATE()), 
('Legal, accounting, design, research and advertising services', '5417', 2, GETUTCDATE()), 
('Legal, accounting, design, research and advertising services', '5418', 2, GETUTCDATE()), 
('Legal, accounting, design, research and advertising services', '5419', 2, GETUTCDATE()), 
('Business and building support services (excluding travel)', '5511', 2, GETUTCDATE()), 
('Business and building support services (excluding travel)', '5611', 2, GETUTCDATE()), 
('Business and building support services (excluding travel)', '5612', 2, GETUTCDATE()), 
('Business and building support services (excluding travel)', '5613', 2, GETUTCDATE()), 
('Business and building support services (excluding travel)', '5614', 2, GETUTCDATE()), 
('Travel arrangement services', '5615', 3, GETUTCDATE()), 
('Business and building support services (excluding travel)', '5616', 2, GETUTCDATE()), 
('Business and building support services (excluding travel)', '5617', 2, GETUTCDATE()), 
('Business and building support services (excluding travel)', '5619', 2, GETUTCDATE()), 
('Business and building support services (excluding travel)', '5621', 2, GETUTCDATE()), 
('Business and building support services (excluding travel)', '5622', 2, GETUTCDATE()), 
('Business and building support services (excluding travel)', '5629', 2, GETUTCDATE()), 
('Elementary and secondary schools', '6111', 2, GETUTCDATE()), 
('Community colleges', '6112', 2, GETUTCDATE()), 
('Universities', '6113', 3, GETUTCDATE()), 
('Private and trades education', '6114', 3, GETUTCDATE()), 
('Private and trades education', '6115', 3, GETUTCDATE()), 
('Private and trades education', '6116', 2, GETUTCDATE()), 
('Private and trades education', '6117', 2, GETUTCDATE()), 
('Ambulatory health care services', '6211', 2, GETUTCDATE()), 
('Ambulatory health care services', '6212', 2, GETUTCDATE()), 
('Ambulatory health care services', '6213', 2, GETUTCDATE()), 
('Ambulatory health care services', '6214', 2, GETUTCDATE()), 
('Ambulatory health care services', '6215', 2, GETUTCDATE()), 
('Ambulatory health care services', '6216', 2, GETUTCDATE()), 
('Ambulatory health care services', '6219', 2, GETUTCDATE()), 
('Hospitals', '6221', 2, GETUTCDATE()), 
('Hospitals', '6222', 2, GETUTCDATE()), 
('Hospitals', '6223', 2, GETUTCDATE()), 
('Nursing and residential care facilities', '6231', 2, GETUTCDATE()), 
('Nursing and residential care facilities', '6232', 2, GETUTCDATE()), 
('Nursing and residential care facilities', '6233', 2, GETUTCDATE()), 
('Nursing and residential care facilities', '6239', 2, GETUTCDATE()), 
('Social assistance', '6241', 2, GETUTCDATE()), 
('Social assistance', '6242', 2, GETUTCDATE()), 
('Social assistance', '6243', 2, GETUTCDATE()), 
('Social assistance', '6244', 2, GETUTCDATE()), 
('Performing arts, spectator sports and related industries', '7111', 2, GETUTCDATE()), 
('Performing arts, spectator sports and related industries', '7112', 2, GETUTCDATE()), 
('Performing arts, spectator sports and related industries', '7113', 2, GETUTCDATE()), 
('Performing arts, spectator sports and related industries', '7114', 2, GETUTCDATE()), 
('Performing arts, spectator sports and related industries', '7115', 2, GETUTCDATE()), 
('Museums, galleries and parks', '7121', 2, GETUTCDATE()), 
('Amusement, gambling and recreation industries', '7131', 2, GETUTCDATE()), 
('Amusement, gambling and recreation industries', '7132', 2, GETUTCDATE()), 
('Amusement, gambling and recreation industries', '7139', 2, GETUTCDATE()), 
('Accommodation services', '7211', 2, GETUTCDATE()), 
('Accommodation services', '7212', 2, GETUTCDATE()), 
('Accommodation services', '7213', 2, GETUTCDATE()), 
('Food services and drinking places', '7223', 3, GETUTCDATE()), 
('Food services and drinking places', '7224', 3, GETUTCDATE()), 
('Food services and drinking places', '7225', 3, GETUTCDATE()), 
('Automotive repair and maintenance', '8111', 3, GETUTCDATE()), 
('Personal, non-automotive repair and non-profit services', '8112', 2, GETUTCDATE()), 
('Personal, non-automotive repair and non-profit services', '8113', 2, GETUTCDATE()), 
('Personal, non-automotive repair and non-profit services', '8114', 2, GETUTCDATE()), 
('Personal, non-automotive repair and non-profit services', '8121', 2, GETUTCDATE()), 
('Personal, non-automotive repair and non-profit services', '8122', 2, GETUTCDATE()), 
('Personal, non-automotive repair and non-profit services', '8123', 2, GETUTCDATE()), 
('Personal, non-automotive repair and non-profit services', '8129', 2, GETUTCDATE()), 
('Personal, non-automotive repair and non-profit services', '8131', 2, GETUTCDATE()), 
('Personal, non-automotive repair and non-profit services', '8132', 2, GETUTCDATE()), 
('Personal, non-automotive repair and non-profit services', '8133', 2, GETUTCDATE()), 
('Personal, non-automotive repair and non-profit services', '8134', 2, GETUTCDATE()), 
('Personal, non-automotive repair and non-profit services', '8139', 2, GETUTCDATE()), 
('Personal, non-automotive repair and non-profit services', '8141', 2, GETUTCDATE()), 
('Federal government public administration', '9111', 2, GETUTCDATE()), 
('Federal government public administration', '9112', 2, GETUTCDATE()), 
('Federal government public administration', '9113', 2, GETUTCDATE()), 
('Federal government public administration', '9114', 2, GETUTCDATE()), 
('Federal government public administration', '9119', 2, GETUTCDATE()), 
('Provincial and territorial public administration', '9121', 2, GETUTCDATE()), 
('Provincial and territorial public administration', '9122', 2, GETUTCDATE()), 
('Provincial and territorial public administration', '9129', 2, GETUTCDATE()), 
('Local and Indigenous public administration', '9131', 2, GETUTCDATE()), 
('Local and Indigenous public administration', '9139', 2, GETUTCDATE()), 
('Local and Indigenous public administration', '9141', 2, GETUTCDATE()), 
('Local and Indigenous public administration', '9191', 2, GETUTCDATE());


PRINT 'Done Insert of Industries'