# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on: workflow_dispatch

jobs:
  build:

    runs-on: etg-ci

    steps:
    - uses: actions/checkout@v3
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    - name: NuGet Restore
      run: |
        nuget restore "${{github.workspace}}\ETG.sln"
    - name: MSBuild .NET framework
      run: |
        msbuild.exe "${{github.workspace}}\ETG.sln" /p:platform="Any CPU" /p:configuration="Release"
#    - name: Test .NET
#      run: dotnet test --no-build --verbosity normal
    - name: Publish .NET
      run: dotnet publish "ETG.sln" -o ./Publish -c Release --no-self-contained
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '12.16.1'
    - run: npm install
      working-directory: "CJG.Web.External/UI"
    - run: npm run build
      working-directory: "CJG.Web.External/UI"
#    - run: npm test
    - name: Upload artifacts - frontend
      uses: actions/upload-artifact@v3
      with:
        name: web
        path: CJG.Web.External/UI/obj/Release/Package/PackageTmp
    - name: Upload artifacts - backend
      uses: actions/upload-artifact@v3
      with:
        name: ef
        path: CJG.Infrastructure.EF/bin/Release
