name: Tag

on:
  push:
    tags: ["*"]

jobs:
  main:
    name: main
    runs-on: etg-cd-test

    steps:
    - name: check out repo
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.workflow_run.head_branch }}